### PR TITLE
Add function for coordinates.

### PR DESCRIPTION
**Pull request by benweishi**
Hi, I add one more format. 
If `a=[[x1,y1],[x2,y2],...]`
The new function `to_coords(a, frmt)` will output
`{(x1,y1),(x2,y2), ...}`
This format is useful for plotting data in latex.

If you feel it is useful, please merge it into your package.

### CODE REVIEW

**Comment by josephcslater** [comment]
Very neat! Can you add documentation and examples to the README and the Jupyter notebook showing how to use it?

**Comment by benweishi** [comment]
Sorry for the late reply. 

I noticed that you are putting everything into function `to_ltx`, so I fitted the new format into function `to_ltx` as well. 
I also slightly changed the implementation to make it more readable. You can follow my code pattern as well, `prefix + delimiter.join(list_of_content) + suffix`.
I also added an example to the Jupyter notebook as well.

Let me know what else I can do.

**Comment by benweishi** [comment]
BTW, I'd suggest splitting the function `to_ltx` into three functions: `to_array`, `to_tabular`, and `to_coords`, because:
- The package name already implies that the output will be some latex code.
- `to_clp` is not necessary. You can give an example code in the Jupyter notebook or README to show the user how to copy a string variable into the system clipboard, just like what you are doing for the `lambda` function.
- You may want to add more parameters for customizing the tabular output. 
- Some existing parameters are not necessary for `to_coords` function.
- You may want to be able to output more latex formats.

What do you think?

**Comment by josephcslater** [comment]
I think these are all good ideas. I have to concede, however, that I don't even use this package myself because my job has changed. I'm happy to maintain it, but putting a lot of effort into improving it doesn't make a lot of sense for me. I'm happy to accept pull requests and consider them, though.

**Comment by josephcslater** [comment]
Do you have latex code showing how to plot these outputs?

**Comment by benweishi** [comment]
Here is one: https://timodenk.com/blog/latex-plot-snippets/screen-shot-2017-02-18-at-15-10-07/

Benwei

**Comment by josephcslater** [comment]
I meant, can you put something in the docs as an example with an additional pull request?

**Comment by dbatten5** [comment]
Hi @josephcslater and @benweishi 
I noticed Joseph said that he doesn't have capacity to maintain this package any more so I took it upon myself to re-write it, incorporting some of the suggestions you made on this thread. At the moment it offers just matrix and basic tabular but I'm happy to add more outputs and also consider PRs etc. The package is here https://github.com/dbatten5/arraytex if you'd like to take a look - proper documentation still be written up

**Comment by josephcslater** [comment]
Would it not have been better to just join the project and incorporate updates instead of "yet another" project? If it's the same direction, it just adds confusion to the package ecosystem.

**Comment by dbatten5** [comment]
Well as @benweishi mentioned there was quite a lot of refactoring that could be done, as well as adding tools to automate building and publishing, a testing framework, and linting and codestyle tools on top of that. It's a lot easier to start off with that framework then add the application code on top as opposed to trying to integrate them into existing packages. I looked at the other existing packages and a lot of them haven't been updated for several years. So normally I'd agree with you but I think in this instance it was actually just a lot easier to start again

**Comment by josephcslater** [comment]
I don't disagree with refactoring, etc. Perhaps releasing it same name, but rewritten from scratch as a major release.

**Comment by dbatten5** [comment]
Yep that's a good point, didn't think about that

**Comment by benweishi** [comment]
I think @josephcslater is still actively managing this project. But do let us know when you can't, just don't let it die.
@dbatten5, if you can initialize a new branch, I can contribute some time for the refactoring.

**Comment by josephcslater** [comment]
I won't let it die. I'm just not day-to-day coding, so it take me some time. This project is far enough along that rapid development isn't needed, but I do want to get these inputs into the project. 

FYE: I've maintained the Engineering Vibration Toolbox for 32 year, so... I don't walk away from my projects. (Google Vibration Toolbox)

**Comment by benweishi** [comment]
> I meant, can you put something in the docs as an example with an additional pull request?

In the notebook, I added some latex code of a minimal example which use the `coords` format. I didn't add these to the README, because I want to keep it simple.

**Comment by benweishi** [comment]
I am leaving another note here for future refactoring.
It seems like the general function of this package wants to provide is that, given an array $A$ and a format function $f$, output a string in the format "{prefix} {f(A[0])} {delimiter} {f(A[1])} {delimiter} ... {f(A[n]) {suffix}". Note that the function $f$ can be another recursive call of this function.
So if we do want do the refactoring, we can start with this function, and use this to simplify all other formating.
This general function will be something like
```python
def format(A, prefix, suffix, f)
```
I know `format` is not a good name. But I can't think a better one.
The user can also use this general function to generate their own output.

**Pull request merged**
